
server:
  port: 8085


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Java5TahminDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:

        format_sql: true


